# Generated by Django 4.2.1 on 2023-05-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_board_views"),
        ("chat", "0002_room_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_board",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room",
                to="board.board",
            ),
        ),
    ]
