# Generated by Django 4.2.1 on 2023-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_room_room_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="pw",
            field=models.CharField(default=1234, max_length=4),
            preserve_default=False,
        ),
    ]
